In [1]:
## Import Libs

In [3]:
import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

In [5]:
df = pd.read_csv('/content/Mall_Customers.csv')

In [6]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [8]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [10]:
df.drop('CustomerID', inplace=True, axis=1)

In [15]:
df.columns=['Gender','Age','Annual_Income','Spending_Score(1-100)']

In [16]:
df.describe()

              Age  Annual_Income  Spending_Score(1-100)
count  200.000000     200.000000             200.000000
mean    38.850000      60.560000              50.200000
std     13.969007      26.264721              25.823522
min     18.000000      15.000000               1.000000
25%     28.750000      41.500000              34.750000
50%     36.000000      61.500000              50.000000
75%     49.000000      78.000000              73.000000
max     70.000000     137.000000              99.000000

In [17]:
df.corr()

ValueError: could not convert string to float: 'Male'